# Generated by Django 6.0.4 on 2026-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('on_hold', 'On Hold'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
