# Generated by Django 5.1.1 on 2026-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
