# Generated by Django 5.1.1 on 2026-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_tag_candidatetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='ai_explanation',
            field=models.TextField(blank=True, db_column='ai_explanation', null=True),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='ai_explanation',
            new_name='ats_explanation',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ai_score',
            field=models.IntegerField(blank=True, db_column='ai_score', null=True),
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='ai_score',
            new_name='ats_score',
        ),
    ]
