# Generated by Django 5.1.1 on 2026-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_rename_ai_to_ats'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pool',
            field=models.CharField(choices=[('active', 'Active'), ('duplicate', 'Duplicate')], default='active', max_length=10),
        ),
    ]
