# Generated by Django 6.0.4 on 2026-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='confidence_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='review_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
