# Generated by Django 6.0.4 on 2026-04-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_aievaluation_confidence_and_more'),
        ('jobs', '0002_job_education_level_job_internship_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_range', models.CharField(max_length=10)),
                ('total_candidates', models.IntegerField(default=0)),
                ('shortlisted', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_feedback', to='jobs.job')),
            ],
            options={
                'unique_together': {('job', 'score_range')},
            },
        ),
    ]
