# Generated by Django 5.1.1 on 2026-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_scoringfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
