# Generated by Django 5.1.1 on 2026-05-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_aievaluation_parsed_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='red_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='role_relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
