# Generated by Django 6.0.4 on 2026-04-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('', 'No requirement'), ('any', 'Any degree'), ('bachelors', "Bachelor's degree"), ('masters', "Master's degree"), ('phd', 'PhD')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='internship_policy',
            field=models.CharField(choices=[('full', 'Count as full experience'), ('half', 'Count at 50%'), ('ignore', 'Do not count')], default='half', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='max_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.IntegerField(default=0),
        ),
    ]
