# Generated by Django 5.1.1 on 2026-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_education_level_job_internship_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='knockout_enabled',
            field=models.BooleanField(default=False, help_text='Enable auto-reject for candidates who fail hard requirements'),
        ),
    ]
