# Generated by Django 5.1.1 on 2026-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_knockout_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_weight',
            field=models.FloatField(default=0.15, help_text='Weight for education (0-1)'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_weight',
            field=models.FloatField(default=0.25, help_text='Weight for experience (0-1)'),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_weight',
            field=models.FloatField(default=0.6, help_text='Weight for skill matching (0-1)'),
        ),
    ]
